version: "3.7"

services:
  vscode:
    build: .
    volumes:
      - ../:/workspace
      # SSH directory for Linux, OSX and WSL
      - ~/.ssh:/root/.ssh
      # Shell history persistence
      - ~/.zsh_history:/root/.zsh_history
    environment:
      - TZ=
    cap_add:
      # For debugging with dlv
      - SYS_PTRACE
    security_opt:
      # For debugging with dlv
      - seccomp:unconfined
    entrypoint: [ "zsh", "-c", "while sleep 1000; do :; done" ]
